import { SkillLevel } from '../entity/skill-level.entity';
import { PlayerFormat } from '../player/player-format.enum';

export const SkillLevelSeed: Array<Partial<SkillLevel>> = [
  {
    format: PlayerFormat.NINE,
    pointsRequired: 14,
    skillLevel: 1,
    timeouts: 2,
    tournamentTier: 1,
  },
  {
    format: PlayerFormat.NINE,
    pointsRequired: 19,
    skillLevel: 2,
    timeouts: 2,
    tournamentTier: 1,
  },
  {
    format: PlayerFormat.NINE,
    pointsRequired: 25,
    skillLevel: 3,
    timeouts: 2,
    tournamentTier: 1,
  },
  {
    format: PlayerFormat.NINE,
    pointsRequired: 31,
    skillLevel: 4,
    timeouts: 1,
    tournamentTier: 2,
  },
  {
    format: PlayerFormat.NINE,
    pointsRequired: 38,
    skillLevel: 5,
    timeouts: 1,
    tournamentTier: 2,
  },
  {
    format: PlayerFormat.NINE,
    pointsRequired: 46,
    skillLevel: 6,
    timeouts: 1,
    tournamentTier: 3,
  },
  {
    format: PlayerFormat.NINE,
    pointsRequired: 55,
    skillLevel: 7,
    timeouts: 1,
    tournamentTier: 3,
  },
  {
    format: PlayerFormat.NINE,
    pointsRequired: 65,
    skillLevel: 8,
    timeouts: 1,
    tournamentTier: 3,
  },
  {
    format: PlayerFormat.NINE,
    pointsRequired: 75,
    skillLevel: 9,
    timeouts: 1,
    tournamentTier: 3,
  },
  {
    format: PlayerFormat.EIGHT,
    pointsRequired: 0,
    skillLevel: 1,
    timeouts: 2,
    tournamentTier: 1,
  },
  {
    format: PlayerFormat.EIGHT,
    pointsRequired: 0,
    skillLevel: 2,
    timeouts: 2,
    tournamentTier: 1,
  },
  {
    format: PlayerFormat.EIGHT,
    pointsRequired: 0,
    skillLevel: 3,
    timeouts: 2,
    tournamentTier: 1,
  },
  {
    format: PlayerFormat.EIGHT,
    pointsRequired: 0,
    skillLevel: 4,
    timeouts: 1,
    tournamentTier: 2,
  },
  {
    format: PlayerFormat.EIGHT,
    pointsRequired: 0,
    skillLevel: 5,
    timeouts: 1,
    tournamentTier: 2,
  },
  {
    format: PlayerFormat.EIGHT,
    pointsRequired: 0,
    skillLevel: 6,
    timeouts: 1,
    tournamentTier: 3,
  },
  {
    format: PlayerFormat.EIGHT,
    pointsRequired: 0,
    skillLevel: 7,
    timeouts: 1,
    tournamentTier: 3,
  },
];
